apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: 160.44.200.121:443/otc00000000001000002121/hello-world
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
