apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: test
  name: pvc-test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: test
