#Create a set of ecs with index
heat_template_version: 2015-10-15

description: Advanced template to create a group of ECSes

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance.
    default: Standard_CentOS_7.2_latest
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: s1.medium
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance.
    default: TST4jumphost
  private_network:
    type: string
    label: External Network name or ID
    description: Name of the network which we place the ecs
    default: 3eb8c706-d1e7-40cb-8c45-ad1f0f0f401d

resources:
  tst_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: tstvw_sg
      rules:
        - protocol: tcp
          direction: ingress
          port_range_min: 22
          port_range_max: 65535
        - protocol: tcp
          direction: egress
          port_range_min: 22
          port_range_max: 65535
        - protocol: udp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - protocol: udp
          direction: egress
          port_range_min: 1
          port_range_max: 65535

 resourcegrp_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server
        properties:
          #create a unique name for each server
          #using its index in the group
          name: resourcegrp_%index%
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key }
          security_groups: [{ get_resource: tst_security_group }]
          networks:
            - network: { get_param: private_network }



outputs:
  id:
    description: name of the resource group.
    value: { get_attr: [resourcegrp_group, name] }
  ip:
    description: The ips address of the instance .
    value: { get_attr: [simpleecs, first_address] }
